# Generated by Django 3.0.9 on 2020-10-31 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kpis', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='week_commencing',
            new_name='week_number',
        ),
    ]
