# Generated by Django 3.0.9 on 2020-10-31 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpis', '0002_auto_20201031_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='slug',
            field=models.SlugField(default='', max_length=250, unique=True),
            preserve_default=False,
        ),
    ]
