# Generated by Django 3.0.9 on 2020-10-31 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpis', '0003_report_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='slug',
        ),
        migrations.AddField(
            model_name='customer',
            name='slug',
            field=models.SlugField(default='', max_length=250, unique=True),
            preserve_default=False,
        ),
    ]
