# Generated by Django 3.1.3 on 2020-11-03 12:26

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('kpis', '0004_auto_20201031_1111'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='report',
            managers=[
                ('reports', django.db.models.manager.Manager()),
            ],
        ),
    ]
