# Generated by Django 3.1.3 on 2020-11-03 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kpis', '0005_auto_20201103_1226'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='report',
            managers=[
            ],
        ),
    ]
