# Generated by Django 3.1.3 on 2020-11-07 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpis', '0006_auto_20201103_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='headsets',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
