# Generated by Django 3.1.3 on 2020-11-07 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpis', '0007_report_headsets'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='marketing_cost',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='rent_cost',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='sundries_cost',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
