# Generated by Django 3.1.3 on 2020-11-10 16:36

import django.core.validators
from django.db import migrations, models
import kpis.models


class Migration(migrations.Migration):

    dependencies = [
        ('kpis', '0008_auto_20201110_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='year',
            field=models.PositiveIntegerField(default=kpis.models.default_year, validators=[django.core.validators.MinValueValidator(2018), django.core.validators.MaxValueValidator(2100)]),
        ),
    ]
