# Generated by Django 3.1.3 on 2020-11-10 17:35

import django.core.validators
from django.db import migrations, models
import kpis.models


class Migration(migrations.Migration):

    dependencies = [
        ('kpis', '0009_auto_20201110_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='default_headsets',
            field=models.IntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='report',
            name='marketing_cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='report',
            name='rent_cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='report',
            name='staff_costs',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='report',
            name='sundries_cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='report',
            name='week_number',
            field=models.IntegerField(default=kpis.models.default_week, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(53)]),
        ),
    ]
