# Generated by Django 3.1.3 on 2020-11-07 17:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpis', '0010_auto_20201107_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='week_number',
            field=models.IntegerField(default=1, unique_for_year=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(53)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='report',
            name='year',
            field=models.IntegerField(default=2020, validators=[django.core.validators.MinValueValidator(2018), django.core.validators.MaxValueValidator(2100)]),
            preserve_default=False,
        ),
    ]
