# Generated by Django 3.1.3 on 2020-11-10 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kpis', '0010_auto_20201110_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='default_headsets',
        ),
    ]
