# Generated by Django 3.1.3 on 2020-11-07 17:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpis', '0011_auto_20201107_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='week_number',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(53)]),
        ),
    ]
