# Generated by Django 3.1.3 on 2020-11-10 19:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpis', '0011_remove_customer_default_headsets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='partner_share',
        ),
        migrations.AddField(
            model_name='report',
            name='partner_share_percentage',
            field=models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(90)]),
        ),
    ]
