# Generated by Django 3.1.3 on 2020-11-10 19:17

import django.core.validators
from django.db import migrations, models
import kpis.models


class Migration(migrations.Migration):

    dependencies = [
        ('kpis', '0012_auto_20201110_1912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='partner_share_percentage',
        ),
        migrations.AddField(
            model_name='report',
            name='partner_share',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='report',
            name='gameplays',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='headsets',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='report',
            name='marketing_cost',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='report',
            name='rent_cost',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='report',
            name='staff_costs',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='report',
            name='sundries_cost',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='report',
            name='week_number',
            field=models.PositiveIntegerField(default=kpis.models.default_week, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(53)]),
        ),
    ]
