# Generated by Django 3.1.3 on 2020-11-07 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpis', '0012_auto_20201107_1723'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='report',
            constraint=models.UniqueConstraint(fields=('year', 'week'), name='unique_period'),
        ),
    ]
