# Generated by Django 3.1.3 on 2020-11-13 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpis', '0013_auto_20201110_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='headsets_additions',
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='headsets_basecount',
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
    ]
