# Generated by Django 3.1.3 on 2020-11-13 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpis', '0014_auto_20201113_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='headsets_additions',
            field=models.IntegerField(),
        ),
    ]
