# Generated by Django 3.1.3 on 2020-11-15 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpis', '0016_auto_20201113_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='currency',
            field=models.CharField(blank=True, choices=[('USD', 'USD'), ('GBP', 'GBP'), ('RMB', 'RMB'), ('EUR', 'EUR')], max_length=3, null=True),
        ),
    ]
