# Generated by Django 3.1.3 on 2020-11-17 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpis', '0017_customer_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='currency',
            field=models.CharField(blank=True, choices=[('USD', 'USD'), ('GBP', 'GBP'), ('RMB', 'RMB'), ('EUR', 'EUR'), ('AED', 'AED')], max_length=3, null=True),
        ),
    ]
