# Generated by Django 3.1.3 on 2020-11-19 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpis', '0018_auto_20201117_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='customer_report_received',
            field=models.BooleanField(default=False),
        ),
    ]
