# Generated by Django 3.1.3 on 2020-11-21 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpis', '0019_auto_20201119_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='active',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
