# Generated by Django 3.1.3 on 2020-11-28 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kpis', '0021_auto_20201128_1141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='gbp_revenue',
            new_name='base_revenue',
        ),
    ]
