# Generated by Django 3.1.3 on 2020-11-28 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kpis', '0022_auto_20201128_1741'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='fx_rate_test',
            new_name='fx_rate',
        ),
    ]
