# Generated by Django 3.1.3 on 2020-11-29 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpis', '0023_auto_20201128_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='default_headsets',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
