# Generated by Django 3.1.3 on 2020-11-29 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kpis', '0025_auto_20201129_1107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='customer_report_received',
        ),
    ]
