# Generated by Django 3.1.3 on 2020-11-29 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpis', '0026_remove_report_customer_report_received'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='expected_rev_per_gp',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
