# Generated by Django 3.1.3 on 2020-11-30 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpis', '0028_report_gameplay_variance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='base_revenue',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='revenue',
            field=models.PositiveIntegerField(),
        ),
    ]
