# Generated by Django 3.1.3 on 2020-12-01 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpis', '0029_auto_20201130_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='partner_share_perc',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
