# Generated by Django 3.1.3 on 2020-12-02 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpis', '0030_customer_partner_share_perc'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='contact_accounts',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
