# Generated by Django 3.1.3 on 2020-12-02 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kpis', '0032_auto_20201202_1612'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='contact_first_name',
            new_name='accounts_contact_first_name',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='contact_last_name',
            new_name='accounts_contact_last_name',
        ),
    ]
