# Generated by Django 3.1.3 on 2020-12-02 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kpis', '0033_auto_20201202_1613'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='contact_accounts_email',
            new_name='accounts_contact_email',
        ),
    ]
