# Generated by Django 3.1.3 on 2020-12-08 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kpis', '0035_auto_20201208_0955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='accounts_contact_email',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='accounts_contact_name',
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('department', models.CharField(blank=True, choices=[('Accounts Payable', 'Accounts Payable'), ('Reporting Contact', 'Reporting Contact'), ('Area Manager', 'Area Manager')], max_length=30, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kpis.customer')),
            ],
        ),
    ]
