# Generated by Django 3.1.3 on 2020-12-08 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpis', '0036_auto_20201208_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='notes',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
