# Generated by Django 3.1.3 on 2020-12-08 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpis', '0037_contact_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='notes',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
